version: '3'
services:
  app:
    build: app
    environment:
      - NODE_ENV=production
      - PGHOST=db
    volumes:
      - ./app/var/log/:/usr/app/var/log
    ports:
      - 8080:3000
    depends_on:
      - db

  db:
    image: postgres:12
    env_file:
      - app/.env
    volumes:
      - ./app/db_init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
